services:
  pg_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/cards.sql.gz:/docker-entrypoint-initdb.d/cards.sql.gz
volumes:
  db:
    driver: local